title: Blog by Ben
description: >
  A blog by Ben Kanouse
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Benjamin Kanouse # add your name
author-img: ukulele_ben.jpg # add your photo
about-author: Ruby on Rails developer who loves test-driven development and PostgreSQL. # add description
social-twitter: kanobt61 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: BenKanouse # add your Github handle
social-linkedin: benjamin-kanouse-22a7ba74 # add your Linkedin handle
social-email: kanobt61@gmail.com # add your Email address

# Disqus
discus-identifier: blog-benkanouse-com # add your discus identifier

# Tracker
analytics: UA-127550890-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
